# This is a basic workflow to help you get started with Actions

name: Stage the app


  pull_request:
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Conditional that filters the build job when there is a label called "stage" present
    if: contains(github.event.pull_request.labels.*.name, 'stage')
